### ISSUE TITLE
Exception filter

### ISSUE THREAD

**Issue by viktor-evdokimov** [ByteBlast/c6-equivalents-in-c5#3]
Why not to use `if else throw;` as replacement for:

```
C# 6:

try
{

}
catch (AggregateException ex) if (ex.Data.Count > 1)
{
}
```

i.e.

C# 5:

```
try
{

}
catch (AggregateException ex)
{
    if (ex.Data.Count > 1) {

   } else {
     throw;
  }
}
```

`throw;` keeps stack trace uncut, so it is pretty much same thing.

**Comment by AlexArchive** [comment]
I am verifying that these are equivalent now, thank you.

**Comment by AlexArchive** [comment]
You see, it's not quite the same. Imagine you have something like this:

``` c#
try
{
    throw new AggregateException();
}
catch (AggregateException ex)
{
    if (ex.Data.Count > 1)
    {

    }
    else
    {
        throw;
    }
}
catch (Exception ex)
{
}
```

With an exception filter, the final `catch` would get invoked. When you use the method you describe, it doesn't. Thoughts?

**Comment by bladeoflight16** [comment]
Nasty, but I think it's equivalent to your more complicated example:

```
try
{
    try
    {
        throw new AggregateException();
    }
    catch (AggregateException ex)
    {
        if (ex.Data.Count > 1)
        {
            // Handle it
        }
        else
        {
            throw;
        }
    }
}
catch (Exception ex)
{
    // Handle it
}
```

**Comment by AlexArchive** [comment]
I think I will update the document to include the simple example but include a disclaimer mentioning that it is not exactly the same.

**Comment by bladeoflight16** [comment]
I don't see a reason why you shouldn't include the more complicated one, too, so that the difference is clearer.

**Comment by AlexArchive** [comment]
Good point.

**Comment by AlexArchive** [comment]
Done. Look good?
